services:
  - type: web
    name: chitkara-qualifier-api
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75.0
