spring.application.name=chitkara-qualifier-api
server.port=${PORT:8080}

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.shutdown=graceful

spring.jackson.default-property-inclusion=non_null
spring.mvc.throw-exception-if-no-handler-found=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
